### ISSUE TITLE
mic issue

### ISSUE THREAD

**Issue by realdanked420** [mdingena/att-voodoo#14]
changed my language and tried restarting voodoo but still won't pickup my voice my mic is set to the headset but still won't work

**Comment by mdingena** [comment]
Please download the latest DEBUG setup. When you launch that, Voodoo opens a DevTools window. Make sure you're on the Console tab.

After you have signed in with Alta and are either in the spellcasting interface or on the Waiting for server screen, try to awaken Voodoo by saying `awaken voodoo`. Check the output in the console, it should print the recognised speech every time you say anything.

**Comment by mdingena** [comment]
You haven't responded in a while. I'm closing this issue. Feel free to reopen if you want to provide more information about the problem.
