### ISSUE TITLE
We need an APK version or Port, FAST!!!! I can get it to work on quest 2!!!!!

### ISSUE THREAD

**Issue by UltimateHkge** [mdingena/att-voodoo#57]

**Comment by UltimateHkge** [comment]
I have found a way to make the voice recognition work on quest 2!

**Comment by frankthatank975** [comment]
HOW

> I have found a way to make the voice recognition work on quest 2!

**Comment by mdingena** [comment]
> I have found a way to make the voice recognition work on quest 2!

So what? Voice recognition is not the only problem. Voodoo relies on `spawn string-raw` commands, which Quest ATT game servers do not have access to.
