### ISSUE TITLE
Trying to Log In, gets sent to black webpage.

### ISSUE THREAD

**Issue by PenkLimon** [mdingena/att-voodoo#8]
I've been attempting to log in for 30 minutes. The first time I was sent to the Alta website where it allowed me to use my log-in information. After I did nothing happened. I tried to restart Voodoo. Every time I try to log in now, I get a black webpage, occasionally asking me to open Voodoo even though it's already open. Clicking open does nothing. I have not yet made it passed the authenticating screen.
![image_2021-06-17_201344](https://user-images.githubusercontent.com/86085878/122487191-4a1c0780-cfa0-11eb-92b5-de60ceb47565.png)

**Comment by PenkLimon** [comment]
Update. I have revoked access, given access back. I can still not get passed authenticating.

**Comment by PenkLimon** [comment]
Update. Voodoo has all server permissions in the server and is still not appearing as a supported server.

**Comment by mdingena** [comment]
This issue is resolved: please make sure your system time is accurate. If you change your system clock Voodoo cannot validate tokens returned by Alta.
