### ISSUE TITLE
Voodoo doesn't use my microphone, it picks up nothing I say

### ISSUE THREAD

**Issue by FinnMcv** [mdingena/att-voodoo#9]
I think windows doesn't trust the app to allow microphone access.

**Comment by mdingena** [comment]
It's possible this is related to `English (United States)` missing from Windows Speech settings, as Voodoo is configured to use `en-US`. I'm investigating this further.

**Comment by mdingena** [comment]
Just confirmed with @FinnMcv that doing the following resolved their issue:

- Go to Windows Settings.
- Click the `Time & Language` tile.
- Click the `Language` tab.
- In the `Preferred Languages` section, add `English (United States)`.
- Restart Voodoo.
